# Gitpod Configuration for OpenCog Cognitive Ecosystem
# Complete one-click deployment solution with automated Guix build & deploy process
# Addresses issue #69: docker pull gitpod/workspace-python-3.10:2025-07-23-06-50-33
# Part of madness meta-issue #68

image:
  file: .gitpod.Dockerfile

# Configure the workspace with automated deployment and comprehensive error handling
tasks:
  - name: "Environment Setup"
    init: |
      echo "🔧 Initializing OpenCog Cognitive Ecosystem Environment..."
      ./.gitpod/setup.sh
    command: |
      echo "✅ Environment setup completed"
      echo "Ready for main deployment..."

  - name: "Main Deployment"
    init: |
      echo "🚀 Starting automated deployment with Guix integration..."
      ./.gitpod/deploy.sh
    command: |
      echo ""
      echo "🧠 OpenCog Cognitive Ecosystem Ready!"
      echo "=================================================="
      echo ""
      echo "🌐 Available Services:"
      echo "  • KoboldCpp Web Interface: Port 5001 (auto-forwarded)"
      echo "  • Cognitive Grammar Agent: ./cognitive-grammar-integration-agent.scm"
      echo "  • Package Management: ./ocpkg"
      echo ""
      echo "🚀 Quick Start Commands:"
      echo "  • Test cognitive pipeline: ./test-cognitive-flowchart.sh"
      echo "  • Run demo: ./demo-cognitive-flowchart.sh"
      echo "  • Check deployment status: cat /tmp/deployment-status.txt"
      echo "  • View logs: tail -f /tmp/opencog-deploy.log"
      echo ""
      echo "📚 Documentation:"
      echo "  • Deployment Guide: .gitpod/README.md"
      echo "  • Troubleshooting: .gitpod/TROUBLESHOOTING.md"
      echo "  • Architecture: TECHNICAL-ARCHITECTURE.md"
      echo ""
      echo "🎯 Zero-configuration deployment completed!"

  - name: "KoboldCpp Server (Background)"
    command: |
      echo "⏳ Waiting for deployment to complete..."
      # Wait for main deployment to finish
      while [ ! -f /tmp/deployment-status.txt ] || ! grep -q "completed" /tmp/deployment-status.txt; do
        sleep 5
        echo "Waiting for deployment..."
      done
      echo "🚀 KoboldCpp server starting automatically..."
      # Server started by deploy.sh, this task just monitors
      tail -f /tmp/koboldcpp.log 2>/dev/null || echo "KoboldCpp logs will appear here..."

# Port configuration for KoboldCpp server
ports:
  - port: 5001
    onOpen: open-browser
    name: "KoboldCpp Web Interface"
    description: "Language model inference server with web UI"
    protocol: http

# GitHub integration
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true

# VS Code extensions for development
vscode:
  extensions:
    - ms-python.python
    - ms-python.flake8
    - ms-vscode.makefile-tools
    - redhat.vscode-yaml
    - ms-vscode.vscode-json
    - formulahendry.auto-rename-tag

# Environment variables
env:
  OPENCOG_ECOSYSTEM: "true"
  KOBOLDCPP_PORT: "5001"
  COGNITIVE_GRAMMAR_AGENT: "distributed-cognitive-grammar-agent.scm"
  GITPOD_WORKSPACE_TYPE: "cognitive-ecosystem"